// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package sbi

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

const (
	PayloadSignatureScopes = "PayloadSignature.Scopes"
)

// Defines values for CacheCapabilityAllocationTypes.
const (
	CacheCapabilityAllocationTypesExclusive CacheCapabilityAllocationTypes = "exclusive"
	CacheCapabilityAllocationTypesShared    CacheCapabilityAllocationTypes = "shared"
)

// Defines values for CacheCapabilityLevel.
const (
	CacheCapabilityLevelL1d CacheCapabilityLevel = "L1d"
	CacheCapabilityLevelL1i CacheCapabilityLevel = "L1i"
	CacheCapabilityLevelL2  CacheCapabilityLevel = "L2"
	CacheCapabilityLevelL3  CacheCapabilityLevel = "L3"
)

// Defines values for CacheRequirementAllocation.
const (
	CacheRequirementAllocationExclusive CacheRequirementAllocation = "exclusive"
	CacheRequirementAllocationShared    CacheRequirementAllocation = "shared"
)

// Defines values for CacheRequirementLevel.
const (
	CacheRequirementLevelL1d CacheRequirementLevel = "L1d"
	CacheRequirementLevelL1i CacheRequirementLevel = "L1i"
	CacheRequirementLevelL2  CacheRequirementLevel = "L2"
	CacheRequirementLevelL3  CacheRequirementLevel = "L3"
)

// Defines values for ComponentStatusState.
const (
	ComponentStatusStateFailed     ComponentStatusState = "failed"
	ComponentStatusStateInstalled  ComponentStatusState = "installed"
	ComponentStatusStateInstalling ComponentStatusState = "installing"
	ComponentStatusStatePending    ComponentStatusState = "pending"
	ComponentStatusStateRemoved    ComponentStatusState = "removed"
	ComponentStatusStateRemoving   ComponentStatusState = "removing"
)

// Defines values for DeploymentStatusManifestKind.
const (
	DeploymentStatusManifestKindDeploymentStatusManifest DeploymentStatusManifestKind = "DeploymentStatusManifest"
)

// Defines values for DeploymentStatusManifestStatusState.
const (
	DeploymentStatusManifestStatusStateFailed     DeploymentStatusManifestStatusState = "failed"
	DeploymentStatusManifestStatusStateInstalled  DeploymentStatusManifestStatusState = "installed"
	DeploymentStatusManifestStatusStateInstalling DeploymentStatusManifestStatusState = "installing"
	DeploymentStatusManifestStatusStatePending    DeploymentStatusManifestStatusState = "pending"
	DeploymentStatusManifestStatusStateRemoved    DeploymentStatusManifestStatusState = "removed"
	DeploymentStatusManifestStatusStateRemoving   DeploymentStatusManifestStatusState = "removing"
)

// Defines values for DeviceCapabilitiesManifestKind.
const (
	DeviceCapabilitiesManifestKindDeviceCapabilitiesManifest DeviceCapabilitiesManifestKind = "DeviceCapabilitiesManifest"
)

// Defines values for DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture.
const (
	Amd64 DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture = "amd64"
	Arm   DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture = "arm"
	Arm64 DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture = "arm64"
)

// Defines values for DeviceCapabilitiesManifestPropertiesResourcesCpuKindsClass.
const (
	DeviceCapabilitiesManifestPropertiesResourcesCpuKindsClassEfficiency  DeviceCapabilitiesManifestPropertiesResourcesCpuKindsClass = "efficiency"
	DeviceCapabilitiesManifestPropertiesResourcesCpuKindsClassLowPower    DeviceCapabilitiesManifestPropertiesResourcesCpuKindsClass = "low-power"
	DeviceCapabilitiesManifestPropertiesResourcesCpuKindsClassPerformance DeviceCapabilitiesManifestPropertiesResourcesCpuKindsClass = "performance"
)

// Defines values for DeviceCapabilitiesManifestPropertiesResourcesCpuKindsType.
const (
	DeviceCapabilitiesManifestPropertiesResourcesCpuKindsTypeIsolated DeviceCapabilitiesManifestPropertiesResourcesCpuKindsType = "isolated"
	DeviceCapabilitiesManifestPropertiesResourcesCpuKindsTypeShared   DeviceCapabilitiesManifestPropertiesResourcesCpuKindsType = "shared"
)

// Defines values for DeviceCapabilitiesManifestPropertiesRoles.
const (
	ClusterLeader     DeviceCapabilitiesManifestPropertiesRoles = "Cluster Leader"
	StandaloneCluster DeviceCapabilitiesManifestPropertiesRoles = "Standalone Cluster"
	StandaloneDevice  DeviceCapabilitiesManifestPropertiesRoles = "Standalone Device"
)

// Defines values for DeviceCommunicationInterfaceType.
const (
	Bluetooth DeviceCommunicationInterfaceType = "bluetooth"
	Canbus    DeviceCommunicationInterfaceType = "canbus"
	Cellular  DeviceCommunicationInterfaceType = "cellular"
	Ethernet  DeviceCommunicationInterfaceType = "ethernet"
	Rs232     DeviceCommunicationInterfaceType = "rs232"
	Usb       DeviceCommunicationInterfaceType = "usb"
	Wifi      DeviceCommunicationInterfaceType = "wifi"
)

// Defines values for DevicePeripheralType.
const (
	Camera     DevicePeripheralType = "camera"
	Display    DevicePeripheralType = "display"
	Gpu        DevicePeripheralType = "gpu"
	Microphone DevicePeripheralType = "microphone"
	Speaker    DevicePeripheralType = "speaker"
)

// Defines values for MemoryBandwidthAllocationUnit.
const (
	MBps    MemoryBandwidthAllocationUnit = "MBps"
	Percent MemoryBandwidthAllocationUnit = "percent"
)

// Defines values for MemoryCapabilityBandwidthAllocationTypes.
const (
	PercentThrottling MemoryCapabilityBandwidthAllocationTypes = "percent-throttling"
	RateLimiting      MemoryCapabilityBandwidthAllocationTypes = "rate-limiting"
)

// Defines values for AppDeploymentProfileType.
const (
	Compose AppDeploymentProfileType = "compose"
	Helm    AppDeploymentProfileType = "helm"
)

// Defines values for CpuClass.
const (
	CpuClassEfficiency  CpuClass = "efficiency"
	CpuClassLowPower    CpuClass = "low-power"
	CpuClassPerformance CpuClass = "performance"
)

// Defines values for CpuType.
const (
	CpuTypeIsolated CpuType = "isolated"
	CpuTypeShared   CpuType = "shared"
)

// Defines values for PostApiV1OnboardingJSONBodyKind.
const (
	OnboardingRequest PostApiV1OnboardingJSONBodyKind = "OnboardingRequest"
)

// CacheCapability Cache capability reported by the device
type CacheCapability struct {
	// AllocationTypes Supported cache allocation types. exclusive = dedicated cache partition (requires hardware CAT support), shared = shared cache access.
	AllocationTypes []CacheCapabilityAllocationTypes `json:"allocationTypes"`

	// Level Cache level. L3 = Level 3 Cache, L2 = Level 2 Cache, L1d = Level 1 Data Cache, L1i = Level 1 Instruction Cache.
	Level CacheCapabilityLevel `json:"level"`

	// Size Minimum required cache amount. Value is given in binary units (Ki = Kibibytes, Mi = Mebibytes, Gi = Gibibytes), e.g. "9216Ki".
	Size *string `json:"size,omitempty"`
}

// CacheCapabilityAllocationTypes defines model for CacheCapability.AllocationTypes.
type CacheCapabilityAllocationTypes string

// CacheCapabilityLevel Cache level. L3 = Level 3 Cache, L2 = Level 2 Cache, L1d = Level 1 Data Cache, L1i = Level 1 Instruction Cache.
type CacheCapabilityLevel string

// CacheRequirement Cache requirement requested by an application profile/component
type CacheRequirement struct {
	// Allocation Cache allocation type. exclusive = dedicated cache partition (requires hardware CAT support), shared = shared cache access.
	Allocation CacheRequirementAllocation `json:"allocation"`

	// Level Cache level. L3 = Level 3 Cache, L2 = Level 2 Cache, L1d = Level 1 Data Cache, L1i = Level 1 Instruction Cache.
	Level CacheRequirementLevel `json:"level"`

	// Size Minimum required cache amount. Value is given in binary units (Ki = Kibibytes, Mi = Mebibytes, Gi = Gibibytes), e.g. "9216Ki".
	Size *string `json:"size,omitempty"`
}

// CacheRequirementAllocation Cache allocation type. exclusive = dedicated cache partition (requires hardware CAT support), shared = shared cache access.
type CacheRequirementAllocation string

// CacheRequirementLevel Cache level. L3 = Level 3 Cache, L2 = Level 2 Cache, L1d = Level 1 Data Cache, L1i = Level 1 Instruction Cache.
type CacheRequirementLevel string

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus struct {
	Error *struct {
		Code    *string `json:"code,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"error,omitempty"`
	Name  string               `json:"name"`
	State ComponentStatusState `json:"state"`
}

// ComponentStatusState defines model for ComponentStatus.State.
type ComponentStatusState string

// DeploymentBundleRef Describes a single archive containing all ApplicationDeployment documents. If there are zero deployments (deployments array is empty) the property MUST be present with the value null (it MUST NOT be omitted).
type DeploymentBundleRef struct {
	// Digest The digest of the bundle archive. MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes Rule) in the bundle endpoint's HTTP 200 OK response body.
	Digest *string `json:"digest,omitempty"`

	// MediaType MUST be application/vnd.margo.bundle.v1+tar+gzip; a gzip-compressed tar whose root contains one or more ApplicationDeployment YAML files. If there are zero deployments then bundle MUST be null (an empty archive MUST NOT be served). The archive MUST contain exactly the set of YAML files referenced by deployments.
	MediaType *string `json:"mediaType,omitempty"`

	// SizeBytes Unsigned 64-bit advisory estimate of the decoded payload length in bytes for the bundle archive. Provided for bandwidth estimation and update planning. MUST NOT be used for integrity; digest verification remains mandatory.
	SizeBytes *float32 `json:"sizeBytes,omitempty"`

	// Url Content-addressable retrieval endpoint of the form /api/v1/clients/{clientId}/bundles/{digest} where {digest} equals bundle.digest.
	Url *string `json:"url,omitempty"`
}

// DeploymentManifestRef Reference to a deployment manifest with content addressing and integrity verification.
type DeploymentManifestRef struct {
	// DeploymentId The unique UUID from the ApplicationDeployment's metadata.annotations.id.
	DeploymentId string `json:"deploymentId"`

	// Digest The digest of the individual ApplicationDeployment YAML file. MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes Rule) in that deployment endpoint's HTTP 200 OK response body.
	Digest string `json:"digest"`

	// SizeBytes Unsigned 64-bit advisory estimate of the decoded payload length in bytes for the deployment YAML. Provided for planning or progress display. MUST NOT be used for integrity; digest verification remains mandatory.
	SizeBytes *float32 `json:"sizeBytes,omitempty"`

	// Url Content-addressable endpoint of the form /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest}. The {digest} MUST equal deployments[].digest; the referenced resource is immutable
	Url string `json:"url"`
}

// DeploymentStatusManifest defines model for DeploymentStatusManifest.
type DeploymentStatusManifest struct {
	ApiVersion   string                       `json:"apiVersion"`
	Components   []ComponentStatus            `json:"components"`
	DeploymentId string                       `json:"deploymentId"`
	Kind         DeploymentStatusManifestKind `json:"kind"`
	Status       struct {
		Error *struct {
			Code    *string `json:"code,omitempty"`
			Message *string `json:"message,omitempty"`
		} `json:"error,omitempty"`
		State DeploymentStatusManifestStatusState `json:"state"`
	} `json:"status"`
}

// DeploymentStatusManifestKind defines model for DeploymentStatusManifest.Kind.
type DeploymentStatusManifestKind string

// DeploymentStatusManifestStatusState defines model for DeploymentStatusManifest.Status.State.
type DeploymentStatusManifestStatusState string

// DeviceCapabilitiesManifest defines model for DeviceCapabilitiesManifest.
type DeviceCapabilitiesManifest struct {
	ApiVersion string                         `json:"apiVersion"`
	Kind       DeviceCapabilitiesManifestKind `json:"kind"`
	Properties struct {
		Id          string `json:"id"`
		ModelNumber string `json:"modelNumber"`
		Resources   struct {
			// Cache Cache resources available on the device
			Cache *[]CacheCapability `json:"cache,omitempty"`
			Cpu   struct {
				Architecture *DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture `json:"architecture,omitempty"`
				Cores        float32                                                       `json:"cores"`
				Kinds        *[]struct {
					// Class Core class (P-core, E-core, etc.)
					Class *DeviceCapabilitiesManifestPropertiesResourcesCpuKindsClass `json:"class,omitempty"`
					Cores *float32                                                    `json:"cores,omitempty"`

					// Type Whether these cores are kernel-isolated
					Type *DeviceCapabilitiesManifestPropertiesResourcesCpuKindsType `json:"type,omitempty"`
				} `json:"kinds,omitempty"`
			} `json:"cpu"`
			Interfaces []DeviceCommunicationInterface `json:"interfaces"`

			// Memory Memory capability reported by the device
			Memory      MemoryCapability   `json:"memory"`
			Peripherals []DevicePeripheral `json:"peripherals"`
			Storage     string             `json:"storage"`
		} `json:"resources"`
		Roles        []DeviceCapabilitiesManifestPropertiesRoles `json:"roles"`
		SerialNumber string                                      `json:"serialNumber"`
		Vendor       string                                      `json:"vendor"`
	} `json:"properties"`
}

// DeviceCapabilitiesManifestKind defines model for DeviceCapabilitiesManifest.Kind.
type DeviceCapabilitiesManifestKind string

// DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture defines model for DeviceCapabilitiesManifest.Properties.Resources.Cpu.Architecture.
type DeviceCapabilitiesManifestPropertiesResourcesCpuArchitecture string

// DeviceCapabilitiesManifestPropertiesResourcesCpuKindsClass Core class (P-core, E-core, etc.)
type DeviceCapabilitiesManifestPropertiesResourcesCpuKindsClass string

// DeviceCapabilitiesManifestPropertiesResourcesCpuKindsType Whether these cores are kernel-isolated
type DeviceCapabilitiesManifestPropertiesResourcesCpuKindsType string

// DeviceCapabilitiesManifestPropertiesRoles defines model for DeviceCapabilitiesManifest.Properties.Roles.
type DeviceCapabilitiesManifestPropertiesRoles string

// DeviceCommunicationInterface defines model for DeviceCommunicationInterface.
type DeviceCommunicationInterface struct {
	Type DeviceCommunicationInterfaceType `json:"type"`
}

// DeviceCommunicationInterfaceType defines model for DeviceCommunicationInterface.Type.
type DeviceCommunicationInterfaceType string

// DevicePeripheral defines model for DevicePeripheral.
type DevicePeripheral struct {
	Manufacturer *string              `json:"manufacturer,omitempty"`
	Model        *string              `json:"model,omitempty"`
	Type         DevicePeripheralType `json:"type"`
}

// DevicePeripheralType defines model for DevicePeripheral.Type.
type DevicePeripheralType string

// ManifestVersion Monotonically increasing unsigned 64-bit integer in the inclusive range [1, 2^64-1]. Prevents rollback attacks. The first manifest MUST use 1.
type ManifestVersion = float32

// MemoryBandwidthAllocation Memory bandwidth allocation requested by a workload
type MemoryBandwidthAllocation struct {
	// Unit Unit used for memory bandwidth capping. percent = percentage-based cap. MBps = throughput cap in megabytes per second.
	Unit MemoryBandwidthAllocationUnit `json:"unit"`

	// Value Requested bandwidth cap value expressed in the selected unit
	Value int `json:"value"`
}

// MemoryBandwidthAllocationUnit Unit used for memory bandwidth capping. percent = percentage-based cap. MBps = throughput cap in megabytes per second.
type MemoryBandwidthAllocationUnit string

// MemoryCapability Memory capability reported by the device
type MemoryCapability struct {
	// BandwidthAllocationTypes Supported memory bandwidth allocation strategies. percent-throttling = cap memory bandwidth usage by percentage. rate-limiting = cap memory bandwidth to a fixed throughput.
	BandwidthAllocationTypes *[]MemoryCapabilityBandwidthAllocationTypes `json:"bandwidthAllocationTypes,omitempty"`

	// Size Total available memory on the device (e.g., "16Gi")
	Size string `json:"size"`
}

// MemoryCapabilityBandwidthAllocationTypes defines model for MemoryCapability.BandwidthAllocationTypes.
type MemoryCapabilityBandwidthAllocationTypes string

// MemoryRequirement Memory requirement for a deployment profile or component
type MemoryRequirement struct {
	// BandwidthAllocation Memory bandwidth allocation requested by a workload
	BandwidthAllocation *MemoryBandwidthAllocation `json:"bandwidthAllocation,omitempty"`

	// Size Required memory for the deployment profile (e.g., "1Gi")
	Size string `json:"size"`
}

// UnsignedAppStateManifest defines model for UnsignedAppStateManifest.
type UnsignedAppStateManifest struct {
	// Bundle Describes a single archive containing all ApplicationDeployment documents. If there are zero deployments (deployments array is empty) the property MUST be present with the value null (it MUST NOT be omitted).
	Bundle *DeploymentBundleRef `json:"bundle"`

	// Deployments A list of deployment object references for the device. The reference contains some meta info and reference to the url where the deployment is available.
	Deployments []DeploymentManifestRef `json:"deployments"`

	// ManifestVersion Monotonically increasing unsigned 64-bit integer in the inclusive range [1, 2^64-1]. Prevents rollback attacks. The first manifest MUST use 1.
	ManifestVersion ManifestVersion `json:"manifestVersion"`
}

// AppDeploymentManifest Application Deployment manifest
type AppDeploymentManifest struct {
	// ApiVersion API version
	ApiVersion string `json:"apiVersion"`

	// Kind Resource kind
	Kind     string                `json:"kind"`
	Metadata AppDeploymentMetadata `json:"metadata"`

	// Spec Application Deployment specification
	Spec AppDeploymentSpec `json:"spec"`
}

// AppDeploymentMetadata defines model for appDeploymentMetadata.
type AppDeploymentMetadata struct {
	// Annotations Annotations for the resource
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Id Unique identifier for the application deployment
	Id *string `json:"id,omitempty"`

	// Labels Labels for the resource
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Name of the resource
	Name string `json:"name"`

	// Namespace Namespace of the resource
	Namespace *string `json:"namespace,omitempty"`
}

// AppDeploymentParams Application Parameters
type AppDeploymentParams map[string]AppParameterValue

// AppDeploymentProfile Application Deployment Profile
type AppDeploymentProfile struct {
	// Components Components of the deployment profile
	Components []AppDeploymentProfile_Components_Item `json:"components"`

	// RequiredResources Required resources for a deployment profile or component
	RequiredResources *RequiredResources `json:"requiredResources,omitempty"`

	// Type Type of deployment profile
	Type AppDeploymentProfileType `json:"type"`
}

// AppDeploymentProfile_Components_Item defines model for appDeploymentProfile.components.Item.
type AppDeploymentProfile_Components_Item struct {
	union json.RawMessage
}

// AppDeploymentProfileType Type of deployment profile
type AppDeploymentProfileType string

// AppDeploymentSpec Application Deployment specification
type AppDeploymentSpec struct {
	// DeploymentProfile Application Deployment Profile
	DeploymentProfile AppDeploymentProfile `json:"deploymentProfile"`

	// Parameters Application Parameters
	Parameters *AppDeploymentParams `json:"parameters,omitempty"`
}

// AppParameterTarget Application Parameter Target
type AppParameterTarget struct {
	// Components Components of the parameter
	Components []string `json:"components"`

	// Pointer Pointer to the parameter
	Pointer string `json:"pointer"`
}

// AppParameterValue Application Parameter Value
type AppParameterValue struct {
	// Targets Targets of the parameter
	Targets []AppParameterTarget `json:"targets"`

	// Value Value of the parameter
	Value interface{} `json:"value"`
}

// ComposeApplicationDeploymentProfileComponent Compose Application Deployment Profile Component
type ComposeApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// KeyLocation Key location of the component
		KeyLocation *string `json:"keyLocation,omitempty"`

		// PackageLocation The URL indicating the Compose package's location. It should be a direct path to the compose.yaml or compose.yaml file archived in tar.gz
		PackageLocation string `json:"packageLocation"`

		// Timeout Timeout for the component
		Timeout *string `json:"timeout,omitempty"`

		// Wait Wait for the component to be ready
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`

	// RequiredResources Required resources for a deployment profile or component
	RequiredResources *RequiredResources `json:"requiredResources,omitempty"`
}

// Cpu CPU requirement for a workload or deployment profile
type Cpu struct {
	// Architectures Supported CPU architectures
	Architectures *[]string `json:"architectures,omitempty"`

	// Class Core class required by the workload
	Class *CpuClass `json:"class,omitempty"`

	// Cores Required CPU cores
	Cores *float32 `json:"cores,omitempty"`

	// Name Name of the container this CPU requirement applies to
	Name *string `json:"name,omitempty"`

	// Type Whether requested cores must be isolated or can be shared
	Type *CpuType `json:"type,omitempty"`
}

// CpuClass Core class required by the workload
type CpuClass string

// CpuType Whether requested cores must be isolated or can be shared
type CpuType string

// HelmApplicationDeploymentProfileComponent Helm Application Deployment Profile Component
type HelmApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// Repository Repository of the component
		Repository string `json:"repository"`

		// Revision Revision of the component
		Revision *string `json:"revision,omitempty"`

		// Timeout Timeout for the component
		Timeout *string `json:"timeout,omitempty"`

		// Wait Wait for the component to be ready
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`

	// RequiredResources Required resources for a deployment profile or component
	RequiredResources *RequiredResources `json:"requiredResources,omitempty"`
}

// RequiredResources Required resources for a deployment profile or component
type RequiredResources struct {
	// Cache Cache requirements for the deployment profile or component
	Cache *[]CacheRequirement `json:"cache,omitempty"`

	// Cpu CPU requirements for the deployment profile
	Cpu *[]Cpu `json:"cpu,omitempty"`

	// Memory Memory requirement for a deployment profile or component
	Memory *MemoryRequirement `json:"memory,omitempty"`

	// Storage Required storage for the deployment profile
	Storage *string `json:"storage,omitempty"`
}

// GetApiV1ClientsClientIdBundlesDigestParams defines parameters for GetApiV1ClientsClientIdBundlesDigest.
type GetApiV1ClientsClientIdBundlesDigestParams struct {
	// IfNoneMatch Quoted ETag (same as digest) previously returned for this bundle.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// GetApiV1ClientsClientIdDeploymentsParams defines parameters for GetApiV1ClientsClientIdDeployments.
type GetApiV1ClientsClientIdDeploymentsParams struct {
	// IfNoneMatch ETag value of the last successfully synced manifest. The ETag is returned to the client from the /deployments endpoint, it is the digest of the state manifest.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Accept Indicates which manifest formats the client supports. Supported values: application/vnd.margo.manifest.v1+json.
	Accept *string `json:"Accept,omitempty"`
}

// GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams defines parameters for GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest.
type GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams struct {
	// IfNoneMatch Optional ETag for caching. The ETag is returned to the client from the /deployments endpoint, it is the digest of the state manifest.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// AcceptEncoding Indicates supported compression formats (e.g., gzip, br)
	AcceptEncoding *string `json:"Accept-Encoding,omitempty"`
}

// PostApiV1OnboardingJSONBody defines parameters for PostApiV1Onboarding.
type PostApiV1OnboardingJSONBody struct {
	// ApiVersion API version identifier
	ApiVersion string `json:"apiVersion"`

	// Certificate Base64-encoded client certificate
	Certificate string `json:"certificate"`

	// Kind Resource kind
	Kind PostApiV1OnboardingJSONBodyKind `json:"kind"`
}

// PostApiV1OnboardingJSONBodyKind defines parameters for PostApiV1Onboarding.
type PostApiV1OnboardingJSONBodyKind string

// PostApiV1ClientsClientIdCapabilitiesJSONRequestBody defines body for PostApiV1ClientsClientIdCapabilities for application/json ContentType.
type PostApiV1ClientsClientIdCapabilitiesJSONRequestBody = DeviceCapabilitiesManifest

// PutApiV1ClientsClientIdCapabilitiesJSONRequestBody defines body for PutApiV1ClientsClientIdCapabilities for application/json ContentType.
type PutApiV1ClientsClientIdCapabilitiesJSONRequestBody = DeviceCapabilitiesManifest

// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody defines body for PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus for application/json ContentType.
type PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody = DeploymentStatusManifest

// PostApiV1OnboardingJSONRequestBody defines body for PostApiV1Onboarding for application/json ContentType.
type PostApiV1OnboardingJSONRequestBody PostApiV1OnboardingJSONBody

// AsHelmApplicationDeploymentProfileComponent returns the union data inside the AppDeploymentProfile_Components_Item as a HelmApplicationDeploymentProfileComponent
func (t AppDeploymentProfile_Components_Item) AsHelmApplicationDeploymentProfileComponent() (HelmApplicationDeploymentProfileComponent, error) {
	var body HelmApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHelmApplicationDeploymentProfileComponent overwrites any union data inside the AppDeploymentProfile_Components_Item as the provided HelmApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) FromHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHelmApplicationDeploymentProfileComponent performs a merge with any union data inside the AppDeploymentProfile_Components_Item, using the provided HelmApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) MergeHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsComposeApplicationDeploymentProfileComponent returns the union data inside the AppDeploymentProfile_Components_Item as a ComposeApplicationDeploymentProfileComponent
func (t AppDeploymentProfile_Components_Item) AsComposeApplicationDeploymentProfileComponent() (ComposeApplicationDeploymentProfileComponent, error) {
	var body ComposeApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeApplicationDeploymentProfileComponent overwrites any union data inside the AppDeploymentProfile_Components_Item as the provided ComposeApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) FromComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeApplicationDeploymentProfileComponent performs a merge with any union data inside the AppDeploymentProfile_Components_Item, using the provided ComposeApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) MergeComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t AppDeploymentProfile_Components_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AppDeploymentProfile_Components_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
