// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package sbi

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ComponentStatusState.
const (
	ComponentStatusStateFailed     ComponentStatusState = "failed"
	ComponentStatusStateInstalled  ComponentStatusState = "installed"
	ComponentStatusStateInstalling ComponentStatusState = "installing"
	ComponentStatusStatePending    ComponentStatusState = "pending"
	ComponentStatusStateRemoved    ComponentStatusState = "removed"
	ComponentStatusStateRemoving   ComponentStatusState = "removing"
)

// Valid indicates whether the value is a known member of the ComponentStatusState enum.
func (e ComponentStatusState) Valid() bool {
	switch e {
	case ComponentStatusStateFailed:
		return true
	case ComponentStatusStateInstalled:
		return true
	case ComponentStatusStateInstalling:
		return true
	case ComponentStatusStatePending:
		return true
	case ComponentStatusStateRemoved:
		return true
	case ComponentStatusStateRemoving:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentStatusManifestKind.
const (
	DeploymentStatusManifestKindDeploymentStatusManifest DeploymentStatusManifestKind = "DeploymentStatusManifest"
)

// Valid indicates whether the value is a known member of the DeploymentStatusManifestKind enum.
func (e DeploymentStatusManifestKind) Valid() bool {
	switch e {
	case DeploymentStatusManifestKindDeploymentStatusManifest:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentStatusManifestStatusState.
const (
	DeploymentStatusManifestStatusStateFailed     DeploymentStatusManifestStatusState = "failed"
	DeploymentStatusManifestStatusStateInstalled  DeploymentStatusManifestStatusState = "installed"
	DeploymentStatusManifestStatusStateInstalling DeploymentStatusManifestStatusState = "installing"
	DeploymentStatusManifestStatusStatePending    DeploymentStatusManifestStatusState = "pending"
	DeploymentStatusManifestStatusStateRemoved    DeploymentStatusManifestStatusState = "removed"
	DeploymentStatusManifestStatusStateRemoving   DeploymentStatusManifestStatusState = "removing"
)

// Valid indicates whether the value is a known member of the DeploymentStatusManifestStatusState enum.
func (e DeploymentStatusManifestStatusState) Valid() bool {
	switch e {
	case DeploymentStatusManifestStatusStateFailed:
		return true
	case DeploymentStatusManifestStatusStateInstalled:
		return true
	case DeploymentStatusManifestStatusStateInstalling:
		return true
	case DeploymentStatusManifestStatusStatePending:
		return true
	case DeploymentStatusManifestStatusStateRemoved:
		return true
	case DeploymentStatusManifestStatusStateRemoving:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestKind.
const (
	DeviceCapabilitiesManifestKindDeviceCapabilitiesManifest DeviceCapabilitiesManifestKind = "DeviceCapabilitiesManifest"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestKind enum.
func (e DeviceCapabilitiesManifestKind) Valid() bool {
	switch e {
	case DeviceCapabilitiesManifestKindDeviceCapabilitiesManifest:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesCacheAllocationTypes.
const (
	DeviceCapabilitiesManifestPropertiesCacheAllocationTypesExclusive DeviceCapabilitiesManifestPropertiesCacheAllocationTypes = "exclusive"
	DeviceCapabilitiesManifestPropertiesCacheAllocationTypesShared    DeviceCapabilitiesManifestPropertiesCacheAllocationTypes = "shared"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesCacheAllocationTypes enum.
func (e DeviceCapabilitiesManifestPropertiesCacheAllocationTypes) Valid() bool {
	switch e {
	case DeviceCapabilitiesManifestPropertiesCacheAllocationTypesExclusive:
		return true
	case DeviceCapabilitiesManifestPropertiesCacheAllocationTypesShared:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesCacheLevel.
const (
	DeviceCapabilitiesManifestPropertiesCacheLevelL1d DeviceCapabilitiesManifestPropertiesCacheLevel = "L1d"
	DeviceCapabilitiesManifestPropertiesCacheLevelL1i DeviceCapabilitiesManifestPropertiesCacheLevel = "L1i"
	DeviceCapabilitiesManifestPropertiesCacheLevelL2  DeviceCapabilitiesManifestPropertiesCacheLevel = "L2"
	DeviceCapabilitiesManifestPropertiesCacheLevelL3  DeviceCapabilitiesManifestPropertiesCacheLevel = "L3"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesCacheLevel enum.
func (e DeviceCapabilitiesManifestPropertiesCacheLevel) Valid() bool {
	switch e {
	case DeviceCapabilitiesManifestPropertiesCacheLevelL1d:
		return true
	case DeviceCapabilitiesManifestPropertiesCacheLevelL1i:
		return true
	case DeviceCapabilitiesManifestPropertiesCacheLevelL2:
		return true
	case DeviceCapabilitiesManifestPropertiesCacheLevelL3:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesCpusArchitecture.
const (
	Amd64 DeviceCapabilitiesManifestPropertiesCpusArchitecture = "amd64"
	Arm   DeviceCapabilitiesManifestPropertiesCpusArchitecture = "arm"
	Arm64 DeviceCapabilitiesManifestPropertiesCpusArchitecture = "arm64"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesCpusArchitecture enum.
func (e DeviceCapabilitiesManifestPropertiesCpusArchitecture) Valid() bool {
	switch e {
	case Amd64:
		return true
	case Arm:
		return true
	case Arm64:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesCpusKindsClass.
const (
	DeviceCapabilitiesManifestPropertiesCpusKindsClassEfficiency  DeviceCapabilitiesManifestPropertiesCpusKindsClass = "efficiency"
	DeviceCapabilitiesManifestPropertiesCpusKindsClassLowPower    DeviceCapabilitiesManifestPropertiesCpusKindsClass = "low-power"
	DeviceCapabilitiesManifestPropertiesCpusKindsClassPerformance DeviceCapabilitiesManifestPropertiesCpusKindsClass = "performance"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesCpusKindsClass enum.
func (e DeviceCapabilitiesManifestPropertiesCpusKindsClass) Valid() bool {
	switch e {
	case DeviceCapabilitiesManifestPropertiesCpusKindsClassEfficiency:
		return true
	case DeviceCapabilitiesManifestPropertiesCpusKindsClassLowPower:
		return true
	case DeviceCapabilitiesManifestPropertiesCpusKindsClassPerformance:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesCpusKindsType.
const (
	DeviceCapabilitiesManifestPropertiesCpusKindsTypeIsolated DeviceCapabilitiesManifestPropertiesCpusKindsType = "isolated"
	DeviceCapabilitiesManifestPropertiesCpusKindsTypeShared   DeviceCapabilitiesManifestPropertiesCpusKindsType = "shared"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesCpusKindsType enum.
func (e DeviceCapabilitiesManifestPropertiesCpusKindsType) Valid() bool {
	switch e {
	case DeviceCapabilitiesManifestPropertiesCpusKindsTypeIsolated:
		return true
	case DeviceCapabilitiesManifestPropertiesCpusKindsTypeShared:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes.
const (
	DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesCompose DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes = "compose"
	DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesHelm    DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes = "helm"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes enum.
func (e DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes) Valid() bool {
	switch e {
	case DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesCompose:
		return true
	case DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypesHelm:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCapabilitiesManifestPropertiesSupportedRuntimes.
const (
	Oci DeviceCapabilitiesManifestPropertiesSupportedRuntimes = "oci"
)

// Valid indicates whether the value is a known member of the DeviceCapabilitiesManifestPropertiesSupportedRuntimes enum.
func (e DeviceCapabilitiesManifestPropertiesSupportedRuntimes) Valid() bool {
	switch e {
	case Oci:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCommunicationInterfaceType.
const (
	Bluetooth DeviceCommunicationInterfaceType = "bluetooth"
	Canbus    DeviceCommunicationInterfaceType = "canbus"
	Cellular  DeviceCommunicationInterfaceType = "cellular"
	Ethernet  DeviceCommunicationInterfaceType = "ethernet"
	Rs232     DeviceCommunicationInterfaceType = "rs232"
	Usb       DeviceCommunicationInterfaceType = "usb"
	Wifi      DeviceCommunicationInterfaceType = "wifi"
)

// Valid indicates whether the value is a known member of the DeviceCommunicationInterfaceType enum.
func (e DeviceCommunicationInterfaceType) Valid() bool {
	switch e {
	case Bluetooth:
		return true
	case Canbus:
		return true
	case Cellular:
		return true
	case Ethernet:
		return true
	case Rs232:
		return true
	case Usb:
		return true
	case Wifi:
		return true
	default:
		return false
	}
}

// Defines values for DevicePeripheralType.
const (
	Camera     DevicePeripheralType = "camera"
	Display    DevicePeripheralType = "display"
	Gpu        DevicePeripheralType = "gpu"
	Microphone DevicePeripheralType = "microphone"
	Speaker    DevicePeripheralType = "speaker"
)

// Valid indicates whether the value is a known member of the DevicePeripheralType enum.
func (e DevicePeripheralType) Valid() bool {
	switch e {
	case Camera:
		return true
	case Display:
		return true
	case Gpu:
		return true
	case Microphone:
		return true
	case Speaker:
		return true
	default:
		return false
	}
}

// Defines values for AppDeploymentProfileType.
const (
	AppDeploymentProfileTypeCompose AppDeploymentProfileType = "compose"
	AppDeploymentProfileTypeHelm    AppDeploymentProfileType = "helm"
)

// Valid indicates whether the value is a known member of the AppDeploymentProfileType enum.
func (e AppDeploymentProfileType) Valid() bool {
	switch e {
	case AppDeploymentProfileTypeCompose:
		return true
	case AppDeploymentProfileTypeHelm:
		return true
	default:
		return false
	}
}

// Defines values for CacheAllocation.
const (
	CacheAllocationExclusive CacheAllocation = "exclusive"
	CacheAllocationShared    CacheAllocation = "shared"
)

// Valid indicates whether the value is a known member of the CacheAllocation enum.
func (e CacheAllocation) Valid() bool {
	switch e {
	case CacheAllocationExclusive:
		return true
	case CacheAllocationShared:
		return true
	default:
		return false
	}
}

// Defines values for CacheLevel.
const (
	CacheLevelL1d CacheLevel = "L1d"
	CacheLevelL1i CacheLevel = "L1i"
	CacheLevelL2  CacheLevel = "L2"
	CacheLevelL3  CacheLevel = "L3"
)

// Valid indicates whether the value is a known member of the CacheLevel enum.
func (e CacheLevel) Valid() bool {
	switch e {
	case CacheLevelL1d:
		return true
	case CacheLevelL1i:
		return true
	case CacheLevelL2:
		return true
	case CacheLevelL3:
		return true
	default:
		return false
	}
}

// Defines values for CpuClass.
const (
	CpuClassEfficiency  CpuClass = "efficiency"
	CpuClassLowPower    CpuClass = "low-power"
	CpuClassPerformance CpuClass = "performance"
)

// Valid indicates whether the value is a known member of the CpuClass enum.
func (e CpuClass) Valid() bool {
	switch e {
	case CpuClassEfficiency:
		return true
	case CpuClassLowPower:
		return true
	case CpuClassPerformance:
		return true
	default:
		return false
	}
}

// Defines values for CpuType.
const (
	CpuTypeIsolated CpuType = "isolated"
	CpuTypeShared   CpuType = "shared"
)

// Valid indicates whether the value is a known member of the CpuType enum.
func (e CpuType) Valid() bool {
	switch e {
	case CpuTypeIsolated:
		return true
	case CpuTypeShared:
		return true
	default:
		return false
	}
}

// Defines values for PostApiV1OnboardingJSONBodyKind.
const (
	OnboardingRequest PostApiV1OnboardingJSONBodyKind = "OnboardingRequest"
)

// Valid indicates whether the value is a known member of the PostApiV1OnboardingJSONBodyKind enum.
func (e PostApiV1OnboardingJSONBodyKind) Valid() bool {
	switch e {
	case OnboardingRequest:
		return true
	default:
		return false
	}
}

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus struct {
	Error *struct {
		Code    *string `json:"code,omitempty"`
		Message *string `json:"message,omitempty"`
		Source  *string `json:"source,omitempty"`
	} `json:"error,omitempty"`
	Name  string               `json:"name"`
	State ComponentStatusState `json:"state"`
}

// ComponentStatusState defines model for ComponentStatus.State.
type ComponentStatusState string

// DeploymentBundleRef Describes a single archive containing all ApplicationDeployment documents. If there are zero deployments (deployments array is empty) the property MUST be present with the value null (it MUST NOT be omitted).
type DeploymentBundleRef struct {
	// Digest The digest of the bundle archive. MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes Rule) in the bundle endpoint's HTTP 200 OK response body.
	Digest *string `json:"digest,omitempty"`

	// MediaType MUST be application/vnd.margo.bundle.v1+tar+gzip; a gzip-compressed tar whose root contains one or more ApplicationDeployment YAML files. If there are zero deployments then bundle MUST be null (an empty archive MUST NOT be served). The archive MUST contain exactly the set of YAML files referenced by deployments.
	MediaType *string `json:"mediaType,omitempty"`

	// SizeBytes Unsigned 64-bit advisory estimate of the decoded payload length in bytes for the bundle archive. Provided for bandwidth estimation and update planning. MUST NOT be used for integrity; digest verification remains mandatory.
	SizeBytes *float32 `json:"sizeBytes,omitempty"`

	// Url Content-addressable retrieval endpoint of the form /api/v1/clients/{clientId}/bundles/{digest} where {digest} equals bundle.digest.
	Url *string `json:"url,omitempty"`
}

// DeploymentManifestRef Reference to a deployment manifest with content addressing and integrity verification.
type DeploymentManifestRef struct {
	// DeploymentId Unique identifier for the application deployment.
	DeploymentId string `json:"deploymentId"`

	// Digest The digest of the individual ApplicationDeployment YAML file. MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes Rule) in that deployment endpoint's HTTP 200 OK response body.
	Digest string `json:"digest"`

	// SizeBytes Unsigned 64-bit advisory estimate of the decoded payload length in bytes for the deployment YAML. Provided for planning or progress display. MUST NOT be used for integrity; digest verification remains mandatory.
	SizeBytes *float32 `json:"sizeBytes,omitempty"`

	// Url Content-addressable endpoint of the form /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest}. The {digest} MUST equal deployments[].digest; the referenced resource is immutable
	Url string `json:"url"`
}

// DeploymentStatusManifest defines model for DeploymentStatusManifest.
type DeploymentStatusManifest struct {
	ApiVersion   string                       `json:"apiVersion"`
	Components   []ComponentStatus            `json:"components"`
	DeploymentId string                       `json:"deploymentId"`
	DeviceId     *DeviceId                    `json:"deviceId,omitempty"`
	Kind         DeploymentStatusManifestKind `json:"kind"`
	Status       struct {
		Error *struct {
			Code    *string `json:"code,omitempty"`
			Message *string `json:"message,omitempty"`
			Source  *string `json:"source,omitempty"`
		} `json:"error,omitempty"`
		State DeploymentStatusManifestStatusState `json:"state"`
	} `json:"status"`
}

// DeploymentStatusManifestKind defines model for DeploymentStatusManifest.Kind.
type DeploymentStatusManifestKind string

// DeploymentStatusManifestStatusState defines model for DeploymentStatusManifest.Status.State.
type DeploymentStatusManifestStatusState string

// DeviceCapabilitiesManifest defines model for DeviceCapabilitiesManifest.
type DeviceCapabilitiesManifest struct {
	ApiVersion string                         `json:"apiVersion"`
	Kind       DeviceCapabilitiesManifestKind `json:"kind"`
	Properties struct {
		// Cache Cache resources available on the device
		Cache *[]struct {
			// AllocationTypes Cache allocation types supported by the device. exclusive = device supports dedicated cache partitioning, shared = device supports shared cache access.
			AllocationTypes []DeviceCapabilitiesManifestPropertiesCacheAllocationTypes `json:"allocationTypes"`

			// Level Cache level. L3 = Level 3 Cache, L2 = Level 2 Cache, L1d = Level 1 Data Cache, L1i = Level 1 Instruction Cache.
			Level DeviceCapabilitiesManifestPropertiesCacheLevel `json:"level"`

			// Size Minimum required cache amount. Value is given in binary units (Ki = Kibibytes, Mi = Mebibytes, Gi = Gibibytes), e.g. "9216Ki".
			Size string `json:"size"`
		} `json:"cache,omitempty"`
		Cpus *[]struct {
			Architecture *DeviceCapabilitiesManifestPropertiesCpusArchitecture `json:"architecture,omitempty"`
			Cores        float32                                               `json:"cores"`
			Kinds        *[]struct {
				// Class Core class (P-core, E-core, etc.)
				Class *DeviceCapabilitiesManifestPropertiesCpusKindsClass `json:"class,omitempty"`
				Cores *float32                                            `json:"cores,omitempty"`

				// Frequency Frequency characteristics for this core kind
				Frequency *struct {
					// BaseMHz Base CPU frequency in MHz
					BaseMHz *float32 `json:"baseMHz,omitempty"`

					// MaxMHz Maximum achievable CPU frequency in MHz
					MaxMHz *float32 `json:"maxMHz,omitempty"`
				} `json:"frequency,omitempty"`

				// Type Whether these cores are kernel-isolated
				Type *DeviceCapabilitiesManifestPropertiesCpusKindsType `json:"type,omitempty"`
			} `json:"kinds,omitempty"`
		} `json:"cpus,omitempty"`
		Id                       DeviceId                                                        `json:"id"`
		Interfaces               *[]DeviceCommunicationInterface                                 `json:"interfaces,omitempty"`
		Memory                   *string                                                         `json:"memory,omitempty"`
		ModelNumber              string                                                          `json:"modelNumber"`
		OtelCollector            *bool                                                           `json:"otelCollector,omitempty"`
		Peripherals              *[]DevicePeripheral                                             `json:"peripherals,omitempty"`
		SerialNumber             string                                                          `json:"serialNumber"`
		Storage                  *string                                                         `json:"storage,omitempty"`
		SupportedDeploymentTypes *[]DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes `json:"supportedDeploymentTypes,omitempty"`
		SupportedRuntimes        *[]DeviceCapabilitiesManifestPropertiesSupportedRuntimes        `json:"supportedRuntimes,omitempty"`
		Vendor                   string                                                          `json:"vendor"`
	} `json:"properties"`
}

// DeviceCapabilitiesManifestKind defines model for DeviceCapabilitiesManifest.Kind.
type DeviceCapabilitiesManifestKind string

// DeviceCapabilitiesManifestPropertiesCacheAllocationTypes defines model for DeviceCapabilitiesManifest.Properties.Cache.AllocationTypes.
type DeviceCapabilitiesManifestPropertiesCacheAllocationTypes string

// DeviceCapabilitiesManifestPropertiesCacheLevel Cache level. L3 = Level 3 Cache, L2 = Level 2 Cache, L1d = Level 1 Data Cache, L1i = Level 1 Instruction Cache.
type DeviceCapabilitiesManifestPropertiesCacheLevel string

// DeviceCapabilitiesManifestPropertiesCpusArchitecture defines model for DeviceCapabilitiesManifest.Properties.Cpus.Architecture.
type DeviceCapabilitiesManifestPropertiesCpusArchitecture string

// DeviceCapabilitiesManifestPropertiesCpusKindsClass Core class (P-core, E-core, etc.)
type DeviceCapabilitiesManifestPropertiesCpusKindsClass string

// DeviceCapabilitiesManifestPropertiesCpusKindsType Whether these cores are kernel-isolated
type DeviceCapabilitiesManifestPropertiesCpusKindsType string

// DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes defines model for DeviceCapabilitiesManifest.Properties.SupportedDeploymentTypes.
type DeviceCapabilitiesManifestPropertiesSupportedDeploymentTypes string

// DeviceCapabilitiesManifestPropertiesSupportedRuntimes defines model for DeviceCapabilitiesManifest.Properties.SupportedRuntimes.
type DeviceCapabilitiesManifestPropertiesSupportedRuntimes string

// DeviceCommunicationInterface defines model for DeviceCommunicationInterface.
type DeviceCommunicationInterface struct {
	Type DeviceCommunicationInterfaceType `json:"type"`
}

// DeviceCommunicationInterfaceType defines model for DeviceCommunicationInterface.Type.
type DeviceCommunicationInterfaceType string

// DeviceId defines model for DeviceId.
type DeviceId = string

// DeviceIdWithAsterisk defines model for DeviceId_with_asterisk.
type DeviceIdWithAsterisk = string

// DevicePeripheral defines model for DevicePeripheral.
type DevicePeripheral struct {
	Manufacturer *string              `json:"manufacturer,omitempty"`
	Model        *string              `json:"model,omitempty"`
	Type         DevicePeripheralType `json:"type"`
}

// DevicePeripheralType defines model for DevicePeripheral.Type.
type DevicePeripheralType string

// ManifestVersion Monotonically increasing unsigned 64-bit integer in the inclusive range [1, 2^64-1]. Prevents rollback attacks. The first manifest MUST use 1.
type ManifestVersion = float32

// UnsignedAppStateManifest defines model for UnsignedAppStateManifest.
type UnsignedAppStateManifest struct {
	// Bundle Describes a single archive containing all ApplicationDeployment documents. If there are zero deployments (deployments array is empty) the property MUST be present with the value null (it MUST NOT be omitted).
	Bundle *DeploymentBundleRef `json:"bundle"`

	// Deployments A list of deployment object references for the device. The reference contains some meta info and reference to the url where the deployment is available.
	Deployments []DeploymentManifestRef `json:"deployments"`

	// ManifestVersion Monotonically increasing unsigned 64-bit integer in the inclusive range [1, 2^64-1]. Prevents rollback attacks. The first manifest MUST use 1.
	ManifestVersion ManifestVersion `json:"manifestVersion"`
}

// AppDeploymentManifest Application Deployment manifest
type AppDeploymentManifest struct {
	// ApiVersion API version
	ApiVersion string `json:"apiVersion"`

	// Id Unique identifier for the application deployment
	Id *string `json:"id,omitempty"`

	// Kind Resource kind
	Kind     string                `json:"kind"`
	Metadata AppDeploymentMetadata `json:"metadata"`

	// Spec Application Deployment specification
	Spec AppDeploymentSpec `json:"spec"`
}

// AppDeploymentMetadata defines model for appDeploymentMetadata.
type AppDeploymentMetadata struct {
	// DeviceId Device ID of the target device for the deployment
	DeviceId DeviceIdWithAsterisk `json:"deviceId"`

	// Labels Labels for the resource
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Name of the resource
	Name string `json:"name"`

	// Namespace Namespace of the resource
	Namespace string `json:"namespace"`
}

// AppDeploymentParams Application Parameters
type AppDeploymentParams map[string]AppParameterValue

// AppDeploymentProfile Application Deployment Profile
type AppDeploymentProfile struct {
	// Components Components of the deployment profile
	Components []AppDeploymentProfile_Components_Item `json:"components"`

	// Type Type of deployment profile
	Type AppDeploymentProfileType `json:"type"`
}

// AppDeploymentProfile_Components_Item defines model for appDeploymentProfile.components.Item.
type AppDeploymentProfile_Components_Item struct {
	union json.RawMessage
}

// AppDeploymentProfileType Type of deployment profile
type AppDeploymentProfileType string

// AppDeploymentSpec Application Deployment specification
type AppDeploymentSpec struct {
	// ApplicationId An identifier for the application. The id is used to help create unique identifiers where required, such as namespaces. The id must be lower case letters and numbers and MAY contain dashes. Uppercase letters, underscores and periods MUST NOT be used. The id MUST NOT be more than 200 characters. The applicationId MUST match the associated application description's top-level "id" attribute.
	ApplicationId string `json:"applicationId"`

	// DeploymentProfile Deployment profile
	DeploymentProfile AppDeploymentProfile `json:"deploymentProfile"`

	// Parameters Parameters for the deployment
	Parameters *AppDeploymentParams `json:"parameters,omitempty"`
}

// AppParameterTarget Application Parameter Target
type AppParameterTarget struct {
	// Components Components of the parameter
	Components []string `json:"components"`

	// Pointer Pointer to the parameter
	Pointer string `json:"pointer"`
}

// AppParameterValue Application Parameter Value
type AppParameterValue struct {
	// Targets Targets of the parameter
	Targets []AppParameterTarget `json:"targets"`

	// Value Value of the parameter
	Value interface{} `json:"value"`
}

// Cache Cache requirement or capability
type Cache struct {
	// Allocation Cache allocation type. exclusive = dedicated cache partition (requires hardware CAT support), shared = shared cache access.
	Allocation CacheAllocation `json:"allocation"`

	// Level Cache level. L3 = Level 3 Cache, L2 = Level 2 Cache, L1d = Level 1 Data Cache, L1i = Level 1 Instruction Cache.
	Level CacheLevel `json:"level"`

	// Size Minimum required cache amount. Value is given in binary units (Ki = Kibibytes, Mi = Mebibytes, Gi = Gibibytes), e.g. "9216Ki".
	Size *string `json:"size,omitempty"`
}

// CacheAllocation Cache allocation type. exclusive = dedicated cache partition (requires hardware CAT support), shared = shared cache access.
type CacheAllocation string

// CacheLevel Cache level. L3 = Level 3 Cache, L2 = Level 2 Cache, L1d = Level 1 Data Cache, L1i = Level 1 Instruction Cache.
type CacheLevel string

// ComposeApplicationDeploymentProfileComponent Compose Application Deployment Profile Component
type ComposeApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// KeyLocation Key location of the component
		KeyLocation *string `json:"keyLocation,omitempty"`

		// PackageLocation The URL indicating the Compose package's location. It should be a direct path to the compose.yaml or compose.yaml file archived in tar.gz
		PackageLocation string `json:"packageLocation"`

		// Timeout Timeout for the component
		Timeout *string `json:"timeout,omitempty"`

		// Wait Wait for the component to be ready
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`

	// RequiredResources Required resources for this component
	RequiredResources *RequiredResources `json:"requiredResources,omitempty"`
}

// Cpu CPU requirement for a workload or deployment profile
type Cpu struct {
	// Architectures Supported CPU architectures
	Architectures *[]string `json:"architectures,omitempty"`

	// Class Core class required by the workload
	Class *CpuClass `json:"class,omitempty"`

	// Cores Required CPU cores
	Cores *float32 `json:"cores,omitempty"`

	// Name Name of the container this CPU requirement applies to
	Name *string `json:"name,omitempty"`

	// Type Whether requested cores must be isolated or can be shared
	Type *CpuType `json:"type,omitempty"`
}

// CpuClass Core class required by the workload
type CpuClass string

// CpuType Whether requested cores must be isolated or can be shared
type CpuType string

// HelmApplicationDeploymentProfileComponent Helm Application Deployment Profile Component
type HelmApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// Repository Repository of the component
		Repository string `json:"repository"`

		// Revision Revision of the component
		Revision *string `json:"revision,omitempty"`

		// Timeout Timeout for the component
		Timeout *string `json:"timeout,omitempty"`

		// Wait Wait for the component to be ready
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`

	// RequiredResources Required resources for this component
	RequiredResources *RequiredResources `json:"requiredResources,omitempty"`
}

// RequiredResources Required resources for a deployment profile or component
type RequiredResources struct {
	// Cache Cache resources available on the device
	Cache *[]Cache `json:"cache,omitempty"`

	// Cpu CPU requirements for the deployment profile
	Cpu *[]Cpu `json:"cpu,omitempty"`

	// Memory Required memory for the deployment profile
	Memory *string `json:"memory,omitempty"`

	// Storage Required storage for the deployment profile
	Storage *string `json:"storage,omitempty"`
}

// GetApiV1ClientsClientIdBundlesDigestParams defines parameters for GetApiV1ClientsClientIdBundlesDigest.
type GetApiV1ClientsClientIdBundlesDigestParams struct {
	// IfNoneMatch Quoted ETag (same as digest) previously returned for this bundle.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// GetApiV1ClientsClientIdDeploymentsParams defines parameters for GetApiV1ClientsClientIdDeployments.
type GetApiV1ClientsClientIdDeploymentsParams struct {
	// IfNoneMatch ETag value of the last successfully synced manifest. The ETag is returned to the client from the /deployments endpoint, it is the digest of the state manifest.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// Accept Indicates which manifest formats the client supports. Supported values: application/vnd.margo.manifest.v1+json.
	Accept *string `json:"Accept,omitempty"`
}

// GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams defines parameters for GetApiV1ClientsClientIdDeploymentsDeploymentIdDigest.
type GetApiV1ClientsClientIdDeploymentsDeploymentIdDigestParams struct {
	// IfNoneMatch Optional ETag for caching. The ETag is returned to the client from the /deployments endpoint, it is the digest of the state manifest.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// AcceptEncoding Indicates supported compression formats (e.g., gzip, br)
	AcceptEncoding *string `json:"Accept-Encoding,omitempty"`
}

// PostApiV1OnboardingJSONBody defines parameters for PostApiV1Onboarding.
type PostApiV1OnboardingJSONBody struct {
	// ApiVersion API version identifier
	ApiVersion string `json:"apiVersion"`

	// Certificate Base64-encoded client certificate
	Certificate string `json:"certificate"`

	// Kind Resource kind
	Kind PostApiV1OnboardingJSONBodyKind `json:"kind"`
}

// PostApiV1OnboardingJSONBodyKind defines parameters for PostApiV1Onboarding.
type PostApiV1OnboardingJSONBodyKind string

// PostApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody defines body for PostApiV1ClientsClientIdCapabilitiesDeviceId for application/json ContentType.
type PostApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody = DeviceCapabilitiesManifest

// PutApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody defines body for PutApiV1ClientsClientIdCapabilitiesDeviceId for application/json ContentType.
type PutApiV1ClientsClientIdCapabilitiesDeviceIdJSONRequestBody = DeviceCapabilitiesManifest

// PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody defines body for PostApiV1ClientsClientIdDeploymentsDeploymentIdStatus for application/json ContentType.
type PostApiV1ClientsClientIdDeploymentsDeploymentIdStatusJSONRequestBody = DeploymentStatusManifest

// PostApiV1OnboardingJSONRequestBody defines body for PostApiV1Onboarding for application/json ContentType.
type PostApiV1OnboardingJSONRequestBody PostApiV1OnboardingJSONBody

// AsHelmApplicationDeploymentProfileComponent returns the union data inside the AppDeploymentProfile_Components_Item as a HelmApplicationDeploymentProfileComponent
func (t AppDeploymentProfile_Components_Item) AsHelmApplicationDeploymentProfileComponent() (HelmApplicationDeploymentProfileComponent, error) {
	var body HelmApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHelmApplicationDeploymentProfileComponent overwrites any union data inside the AppDeploymentProfile_Components_Item as the provided HelmApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) FromHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHelmApplicationDeploymentProfileComponent performs a merge with any union data inside the AppDeploymentProfile_Components_Item, using the provided HelmApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) MergeHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsComposeApplicationDeploymentProfileComponent returns the union data inside the AppDeploymentProfile_Components_Item as a ComposeApplicationDeploymentProfileComponent
func (t AppDeploymentProfile_Components_Item) AsComposeApplicationDeploymentProfileComponent() (ComposeApplicationDeploymentProfileComponent, error) {
	var body ComposeApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeApplicationDeploymentProfileComponent overwrites any union data inside the AppDeploymentProfile_Components_Item as the provided ComposeApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) FromComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeApplicationDeploymentProfileComponent performs a merge with any union data inside the AppDeploymentProfile_Components_Item, using the provided ComposeApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) MergeComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AppDeploymentProfile_Components_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AppDeploymentProfile_Components_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
