#!/bin/bash
# modules/nri.sh - NRI Balloon Resource Policy plugin management
#
# Functions:
#   generate_balloon_policy   - Inspect host CPUs and write a balloons values YAML
#   install_balloon_nri_plugin  - Helm-install the NRI balloon plugin
#   update_balloon_nri_plugin   - Helm-upgrade the NRI balloon plugin
#   uninstall_balloon_nri_plugin - Helm-uninstall the NRI balloon plugin
#
# Prerequisites:
#   - k3s environment with a running device agent
#   - capabilities.sh helpers must be sourced (or this file self-sources them)

SCRIPT_DIR_NRI="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR_NRI}/cpu-topology.sh"

# ---------------------------------------------------------------------------
# generate_balloon_policy
#
# Reads (or builds) the cpu-topology cache and writes a Helm values YAML
# for the nri-resource-policy-balloons chart.
#
# Layout:
#   availableResources.cpu  = cpuset:<all physical core IDs>
#   reservedResources.cpu   = cpuset:0          (core 0 reserved for system)
#   balloonTypes            = one balloon per remaining physical core, named:
#                             <arch>_<p|e|l>_<iso|shrd>_<coreId>
#                             with preferCloseToDevices pointing to the core's
#                             nearest cache sysfs path.
#
# Usage: generate_balloon_policy [output_file [cache_file]]
#   output_file defaults to $HOME/sandbox/balloon-policy.yaml
#   cache_file  defaults to $CPU_TOPOLOGY_CACHE_FILE
# ---------------------------------------------------------------------------
generate_balloon_policy() {
  local output_file="${1:-$HOME/sandbox/balloon-policy.yaml}"
  local cache_file="${2:-$CPU_TOPOLOGY_CACHE_FILE}"

  mkdir -p "$(dirname "$output_file")"

  # Load topology from cache (builds it if absent)
  read_cpu_topology_cache "$cache_file"

  local -a sorted_ids=("${_TOPO_SORTED_IDS[@]}")

  # ---- build cpuset string -----------------------------------------------
  local all_cpuset
  all_cpuset="$(printf '%s\n' "${sorted_ids[@]}" | paste -sd ',' -)"

  # ---- NRI-specific helpers ----------------------------------------------
  _nri_cache_path() {
    local id="$1"
    local base="/sys/devices/system/cpu/cpu${id}/cache"
    if   [[ -d "${base}/index2" ]]; then echo "${base}/index2"
    elif [[ -d "${base}/index1" ]]; then echo "${base}/index1"
    else echo "/sys/devices/system/cpu/cpu${id}"
    fi
  }
  _nri_class_code() {
    case "$1" in
      performance) echo "p" ;;
      efficiency)  echo "e" ;;
      low-power)   echo "l" ;;
      *)           echo "p" ;;
    esac
  }
  _nri_type_code() { [[ "$1" == "isolated" ]] && echo "iso" || echo "shrd"; }

  # ---- emit YAML ---------------------------------------------------------
  {
    cat <<'HEADER'
# Balloon resource policy generated by device-agent.sh
# One balloon per physical core (core 0 reserved for system).
# Naming: <arch>_<p|e|l>_<iso|shrd>_<coreId>
#
# Install:
#   helm repo add nri-plugins https://containers.github.io/nri-plugins
#   helm repo update
#   helm install nri-resource-policy-balloons \
#     nri-plugins/nri-resource-policy-balloons \
#     --namespace kube-system -f balloon-policy.yaml
HEADER

    cat <<PREAMBLE
nri:
  runtime:
    patchConfig: true
  plugin:
    index: 10

config:
  pinCPU: true
  pinMemory: false

  availableResources:
    cpu: "cpuset:${all_cpuset}"

  reservedResources:
    cpu: "cpuset:0"

  balloonTypes:
PREAMBLE

    local cpu_id
    for cpu_id in "${sorted_ids[@]}"; do
      [[ "$cpu_id" -eq 0 ]] && continue
      local meta="${_TOPO_CORE_META[$cpu_id]}"
      local b_arch="${meta%%|*}" rest="${meta#*|}"
      local b_class="${rest%%|*}" b_type="${rest##*|}"
      local class_code; class_code="$(_nri_class_code "$b_class")"
      local type_code;  type_code="$(_nri_type_code  "$b_type")"
      local cache_path; cache_path="$(_nri_cache_path "$cpu_id")"
      cat <<BALLOON
    - name: ${b_arch}_${class_code}_${type_code}_${cpu_id}
      allocatorPriority: high
      minBalloons: 1
      maxBalloons: 1
      minCPUs: 1
      maxCPUs: 1
      preferCloseToDevices:
        - ${cache_path}
BALLOON
    done
  } > "$output_file"

  echo "✅ Balloon policy written to: $output_file"
  echo ""
  echo "Summary of balloons:"
  printf "  %-8s  %-14s  %-12s  %-10s  %s\n" "CoreID" "Architecture" "Class" "Type" "Balloon name"
  printf "  %-8s  %-14s  %-12s  %-10s  %s\n" "------" "------------" "-----" "----" "------------"
  local cpu_id
  for cpu_id in "${sorted_ids[@]}"; do
    [[ "$cpu_id" -eq 0 ]] && continue
    local meta="${_TOPO_CORE_META[$cpu_id]}"
    local b_arch="${meta%%|*}" rest="${meta#*|}"
    local b_class="${rest%%|*}" b_type="${rest##*|}"
    local class_code; class_code="$(_nri_class_code "$b_class")"
    local type_code;  type_code="$(_nri_type_code  "$b_type")"
    printf "  %-8s  %-14s  %-12s  %-10s  %s\n" \
      "$cpu_id" "$b_arch" "$b_class" "$b_type" \
      "${b_arch}_${class_code}_${type_code}_${cpu_id}"
  done
}

# ---------------------------------------------------------------------------
# install_balloon_nri_plugin [values_file]
#   If values_file is omitted or the path does not yet exist the balloon
#   policy is generated automatically from the host's CPU topology first.
# ---------------------------------------------------------------------------
install_balloon_nri_plugin() {
  local values_file="${1:-$HOME/sandbox/balloon-policy.yaml}"

  if [[ ! -f "$values_file" ]]; then
    echo "[INFO] No policy file found at '$values_file' — generating from host CPU topology..."
    if ! generate_balloon_policy "$values_file"; then
      echo "[ERROR] Failed to generate balloon policy."
      return 1
    fi
    echo ""
  fi

  echo "Installing NRI Balloon Resource Policy plugin..."

  if helm repo list 2>/dev/null | awk '{print $1}' | grep -q "^nri-plugins$"; then
    echo "✅ nri-plugins helm repo already added, skipping."
  else
    echo "Adding nri-plugins helm repo..."
    helm repo add nri-plugins https://containers.github.io/nri-plugins
  fi

  helm repo update

  helm install nri-resource-policy-balloons nri-plugins/nri-resource-policy-balloons \
    --namespace kube-system \
    -f "$values_file"

  echo "✅ NRI Balloon Resource Policy plugin installed."
}

# ---------------------------------------------------------------------------
# update_balloon_nri_plugin <values_file>
# ---------------------------------------------------------------------------
update_balloon_nri_plugin() {
  local values_file="${1}"
  if [[ -z "$values_file" ]]; then
    echo "[ERROR] Values file is required."
    echo "Usage: update_balloon_nri_plugin <balloons-values-file>"
    return 1
  fi
  if [[ ! -f "$values_file" ]]; then
    echo "[ERROR] Values file not found: $values_file"
    return 1
  fi

  echo "Upgrading NRI Balloon Resource Policy plugin..."

  helm upgrade nri-resource-policy-balloons nri-plugins/nri-resource-policy-balloons \
    --namespace kube-system \
    -f "$values_file"

  echo "✅ NRI Balloon Resource Policy plugin upgraded."
}

# ---------------------------------------------------------------------------
# uninstall_balloon_nri_plugin
# ---------------------------------------------------------------------------
uninstall_balloon_nri_plugin() {
  echo "Uninstalling NRI Balloon Resource Policy plugin..."
  helm uninstall nri-resource-policy-balloons -n kube-system
  echo "✅ NRI Balloon Resource Policy plugin uninstalled."
}
